### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable exception in devo client

### ISSUE THREAD

**Issue by oshynk** [DevoInc/python-sdk#110] opened 2021-12-02 13:12 UTC
Hi! We are using devo-sdk in Cisco Threat Response integration with Devo and encountered TypeError exception in the client code:

https://github.com/DevoInc/python-sdk/blob/2a135baa3476d667cbde95d9b71d46d5d2d51d27/devo/api/client.py#L322-L330

Here if `first` is equal to `None` and then it's passed to `_is_correct_response` it tries to be sliced and unhandled `TypeError` occurs

https://github.com/DevoInc/python-sdk/blob/2a135baa3476d667cbde95d9b71d46d5d2d51d27/devo/api/client.py#L240-L249

**Comment by oshynk** [comment] 2021-12-03 10:43
Please find the example below:

```
from devo.api import Client, ClientConfig, JSON_SIMPLE

auth = {
    "key": "your_key",
    "secret": "your_secret"
}

address = "apiv2-us.devo.com"
retries = 2
timeout = 25
config = ClientConfig(response="json/simple",
                      processor=JSON_SIMPLE,
                      stream=True)
client = Client(auth=auth, address=address, retries=retries, config=config,
                timeout=timeout)

query = "from all.data where toktains(message, '8.8.8.8')"
dates = {
    "from": "now()-30*day()",
    "to": "now()"
}
limit = 101
response = client.query(query=query, dates=dates, limit=limit)

if __name__ == "__main__":
    [data for data in response]
```

**Comment by pavel-razgovorov** [comment] 2021-12-24 11:52
From what I could have found, it seems like this error happens whenever the query does not return any results. I believe that the best option is to replace this line https://github.com/DevoInc/python-sdk/blob/2a135baa3476d667cbde95d9b71d46d5d2d51d27/devo/api/client.py#L326 with a `return None`.

**Comment by mstoro** [comment] 2022-01-12 10:33
Hi, @pavel-razgovorov! 
Are there any approximate times when this issue fix will be released?

**Comment by pavel-razgovorov** [comment] 2022-01-12 10:44
Hi @mstoro,

This is the last bug I want to fix before uploading a new version, so hopefully once I get the linked PR merged I will start dealing with PyPI's uploads. Please note that the reason we are going slow at these moments is that the previous "main developer" does not maintain this project anymore and hence I still need some time to adapt.

PS: I probably will upload the next release in https://test.pypi.org/ before doing it in the actual PyPI index. Is it OK for you to let me know whenever this new version is uploaded so you can test it from your end to make sure the bug has been corrected, please?

**Comment by mstoro** [comment] 2022-01-12 11:41
Got it, thanks!

Yeap, that won't be a problem, you can reach me when release would be on test index.

**Closed** 2022-01-14 14:25 UTC
Labels: bug

**Comment by pavel-razgovorov** [comment] 2022-01-24 12:30
Hi @mstoro (and @oshynk?),

We finally released the 3.5.0 version in the [Test PyPI index](https://test.pypi.org/project/devo-sdk/). Could you please give it a try and confirm that this bug has been fixed, please? In case it looks OK, we will release the version in the official index soon.

Thanks in advance! And sorry for the huge delay 🤯

**Comment by mstoro** [comment] 2022-01-24 12:42
Hi @pavel-razgovorov,

Thanks a lot! I'll try it in the next couple of days and let you know.

**Comment by mstoro** [comment] 2022-01-26 13:12
Hi @pavel-razgovorov,

I had a chance to try it out, and the error doesn't appear anymore.
We look forward to its release on the official index🙂
Thanks again!

**Comment by pavel-razgovorov** [comment] 2022-01-26 15:06
Perfect @mstoro! The 3.5.0 has been released. Check it out in https://pypi.org/project/devo-sdk/3.5.0/

Glad the issue is solved! 🙌🏻
